data:
  # Directory to store raw SEC filings
  raw_data_dir: 'data/raw'
  # Path to store processed CSV with term analysis results
  processed_data_path: 'data/processed/sec_filings_processed.csv'

sec:
  # List of CIKs to analyze; Add more CIKs as needed
  cik_list:
    - '0000320193'  # Apple Inc.
    - '0000789019'  # Microsoft Corp.
    - '0001652044'  # Alphabet Inc.
    - '0001067983'  # Tesla, Inc.
    - '0001318605'  # Meta Platforms, Inc.
    - '0001018724'  # Nvidia Corp.
    - '0001045810'  # UnitedHealth Group Inc.
    - '0001000180'  # Amazon.com, Inc.
    - '0001551152'  # Berkshire Hathaway Inc.
    - '0001090872'  # Johnson & Johnson
    - '0000732717'  # Intel Corp.
    - '0000200406'  # Procter & Gamble Co.
    - '0000021344'  # AT&T Inc.
    - '0000078003'  # Exxon Mobil Corp.
    - '0000066740'  # General Electric Co.
    - '0001108524'  # Abbott Laboratories
    - '0001326801'  # The Coca-Cola Co.
    - '0000320187'  # Bank of America Corp.
    - '0000072971'  # Boeing Co.
    - '0001104659'  # Wells Fargo & Co.
    - '0000783280'  # McDonald's Corp.
    - '0000313616'  # Ford Motor Co.
    - '0000354950'  # The Home Depot, Inc.
    - '0000051143'  # Chevron Corp.
    - '0000815556'  # Pfizer Inc.
    - '0000060515'  # American Express Co.
    - '0000045810'  # Johnson Controls International
    - '0000877890'  # PayPal Holdings, Inc.
    - '0000092230'  # Verizon Communications Inc.
    - '0000740260'  # Nike, Inc.
    - '0000050863'  # 3M Co.
    - '0001467373'  # Visa Inc.
    - '0000101778'  # Walt Disney Co.
    - '0000079879'  # PepsiCo, Inc.
    - '0000711404'  # Mastercard Inc.
    - '0000829224'  # Qualcomm Inc.
    - '0001403161'  # Netflix, Inc.
    - '0000202058'  # Cisco Systems, Inc.
    - '0000732712'  # Dell Technologies Inc.
    - '0000922224'  # Starbucks Corp.
    - '0000278166'  # Walmart Inc.
    - '0000320196'  # Honeywell International Inc.
    - '0000320155'  # Citigroup Inc.
    - '0001100663'  # Merck & Co., Inc.
    - '0001090434'  # Pepsi Bottling Group, Inc.
    - '0001104657'  # Goldman Sachs Group, Inc.
    - '0001022080'  # Bristol-Myers Squibb Co.
    - '0000314717'  # Caterpillar Inc.
    - '0001106349'  # Netflix, Inc.
    - '0000831001'  # Eli Lilly and Co.
    - '0001107413'  # BlackRock, Inc.

model:
  # Path to save the trained model
  output_path: 'models/sec_filing_classifier.pkl'
  # Additional model parameters (if any)
  parameters:
    max_features: 10000  # Maximum number of features for text vectorization
    test_size: 0.2       # Proportion of dataset to include in the test split
    random_state: 42     # Random seed for reproducibility

nlp:
  # NLP configuration settings
  stopwords: 'english'  # Language for stopwords removal
  max_features: 10000   # Maximum features for vectorization
  min_df: 5             # Minimum document frequency for terms
  max_df: 0.7           # Maximum document frequency for terms

training:
  # Training parameters
  test_size: 0.2        # Fraction of data to be used for testing
  random_state: 42      # Seed for random number generation
  scoring: 'accuracy'   # Metric for model evaluation

logging:
  # Logging configuration
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: INFO
    file:
      class: logging.FileHandler
      filename: logs/app.log  # Save logs to a file
      formatter: simple
      level: INFO
  root:
    level: INFO
    handlers: [console, file]  # Both console and file handlers
